# Generated by Django 3.0.7 on 2020-06-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('UG', (('CS', 'Comp. Sci/ IT Engg.'), ('ECE', 'Electrical & Comm Engg.'), ('EEE', 'Electrical Engg.'), ('MH', 'Mechanical Engg'), ('GN', 'General'))), ('N', 'None')], default='N', max_length=3)),
                ('notifications', models.BooleanField(choices=[(True, 'Notify Me'), (False, "Don't Notify Me")], default=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
